/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class EditProvider extends javax.swing.JDialog {

    private static providersBean pB = new providersBean("", "", "", "", "", "", "", "", "", "", "", "");
    public int id;

    public EditProvider(java.awt.Frame parent, boolean modal, providersBean temp) {
        initComponents();
        Cities();
        TypeAccount();
        Bank();
        jCmbBoxCities.setSelectedItem(null);
        jTxtCities.setVisible(false);
        id = Integer.parseInt(temp.getId());
        this.jTxtLegalName.setText(temp.getLegalName());
        this.jTxtCommercialName.setText(temp.getCommercialName());
        this.jTxtEmail.setText(temp.getEmail());
        this.jTxtPhone.setText(temp.getPhone());
        this.jTxtAddrees.setText(temp.getAddress());
        this.jTxtNameContact.setText(temp.getNameContact());
        this.jTxtAccount.setText(temp.getAccount());

        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/IMG/Logo.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLog_out5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtLegalName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtCommercialName = new javax.swing.JTextField();
        jTxtPhone = new javax.swing.JTextField();
        jCmbBoxTypeAccount = new javax.swing.JComboBox<>();
        jTxtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jTxtAddrees = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtNameContact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCmbBoxCities = new javax.swing.JComboBox<>();
        jCmbBoxState = new javax.swing.JComboBox<>();
        jTxtAccount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCmbBoxBank = new javax.swing.JComboBox<>();
        jTxtCities = new javax.swing.JTextField();
        jTxtTypeAccount = new javax.swing.JTextField();
        jTxtBank = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButtonLog_out5.setBackground(new java.awt.Color(204, 102, 0));
        jButtonLog_out5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLog_out5.setText("Cerrar Sesión");
        jButtonLog_out5.setBorderPainted(false);
        jButtonLog_out5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLog_out5ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ayuda33.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 641, Short.MAX_VALUE)
                .addComponent(jButtonLog_out5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButtonLog_out5))
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("EDITAR PROVEEDOR");

        jPanel4.setBackground(new java.awt.Color(236, 233, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nombre Legal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Dirección");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("No. Cuenta");

        jTxtLegalName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jTxtLegalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLegalNameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nombre Comercial");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Telefono");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ciudad");

        jTxtCommercialName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jTxtPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jCmbBoxTypeAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxTypeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxTypeAccountActionPerformed(evt);
            }
        });

        jTxtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Estado");

        jButton5.setBackground(new java.awt.Color(204, 102, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(204, 102, 0));
        jBtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnUpdate.setText("Actualizar");
        jBtnUpdate.setBorderPainted(false);
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jTxtAddrees.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Nombre Contacto");

        jTxtNameContact.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Banco");

        jCmbBoxCities.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxCitiesActionPerformed(evt);
            }
        });

        jCmbBoxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo" }));
        jCmbBoxState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxStateActionPerformed(evt);
            }
        });

        jTxtAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("T. Cuenta");

        jCmbBoxBank.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxBankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtLegalName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAddrees, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtNameContact, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmbBoxTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTxtAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCommercialName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jCmbBoxCities, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jCmbBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbBoxBank, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 53, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCommercialName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAddrees, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbBoxCities, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNameContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbBoxBank, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbBoxTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jBtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTxtCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCitiesActionPerformed(evt);
            }
        });

        jTxtTypeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTypeAccountActionPerformed(evt);
            }
        });

        jTxtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(397, 397, 397))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTxtTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTypeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLog_out5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLog_out5ActionPerformed
        // TODO add your handling code here:
        Login newframe = new Login();
        newframe.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButtonLog_out5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // CODIGO PARA MANDAR A OTRO JFRAME

        Providers newframe = new Providers();
        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCmbBoxTypeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxTypeAccountActionPerformed
        String TypeAccount = (String) jCmbBoxTypeAccount.getSelectedItem();
        jTxtTypeAccount.setText(String.valueOf(mapTypeAccount.get(TypeAccount)));
    }//GEN-LAST:event_jCmbBoxTypeAccountActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        try {
            updateProviders();
            JOptionPane.showMessageDialog(null, "Proveedor actualizado");
        } catch (IOException ex) {
            Logger.getLogger(EditProvider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jTxtLegalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLegalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLegalNameActionPerformed

    private void jCmbBoxCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxCitiesActionPerformed
        String City = (String) jCmbBoxCities.getSelectedItem();
        jTxtCities.setText(String.valueOf(map.get(City)));
    }//GEN-LAST:event_jCmbBoxCitiesActionPerformed

    private void jCmbBoxStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbBoxStateActionPerformed

    private void jCmbBoxBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxBankActionPerformed
        String Bank = (String) jCmbBoxBank.getSelectedItem();
        jTxtBank.setText(String.valueOf(mapBank.get(Bank)));    }//GEN-LAST:event_jCmbBoxBankActionPerformed

    private void jTxtCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCitiesActionPerformed

    private void jTxtTypeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTypeAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTypeAccountActionPerformed

    private void jTxtBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Proveedor().setVisible(true);
            }
        });*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditProvider frame = new EditProvider(new javax.swing.JFrame(), true, pB);
                frame.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonLog_out5;
    public static javax.swing.JComboBox<String> jCmbBoxBank;
    public static javax.swing.JComboBox<String> jCmbBoxCities;
    public static javax.swing.JComboBox<String> jCmbBoxState;
    public static javax.swing.JComboBox<String> jCmbBoxTypeAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField jTxtAccount;
    private javax.swing.JTextField jTxtAddrees;
    public static javax.swing.JTextField jTxtBank;
    public static javax.swing.JTextField jTxtCities;
    public static javax.swing.JTextField jTxtCommercialName;
    public static javax.swing.JTextField jTxtEmail;
    public static javax.swing.JTextField jTxtLegalName;
    private javax.swing.JTextField jTxtNameContact;
    public static javax.swing.JTextField jTxtPhone;
    public static javax.swing.JTextField jTxtTypeAccount;
    // End of variables declaration//GEN-END:variables
    HashMap<String, Integer> mapBank = new HashMap<>();

    public void Bank() {
        mapBank.put("Bancolombia", 1721);
        mapBank.put("Banco de Bogotá", 1722);
        mapBank.put("Davivienda", 1723);
        mapBank.put("Banco Popular", 1724);
        mapBank.put("BBVA Colombia", 1725);
        for (Map.Entry entry : mapBank.entrySet()) {
            Object Bank = entry.getKey();
            jCmbBoxBank.addItem((String) Bank);
        }
        String Banks = (String) jCmbBoxBank.getSelectedItem();
        jTxtBank.setText(String.valueOf(mapBank.get(Banks)));

    }

    HashMap<String, Integer> mapTypeAccount = new HashMap<>();
    
    public void TypeAccount() {
        mapTypeAccount.put("Cuenta de débito", 1741);
        mapTypeAccount.put("Cuenta de crédito", 1742);
        /*mapTypeAccount.put("Cuenta de débito", 1743);
        mapTypeAccount.put("Cuenta de crédito", 1744);
        mapTypeAccount.put("Cuenta de débito", 1745);
        mapTypeAccount.put("Cuenta de crédito", 1746);
        mapTypeAccount.put("Cuenta de débito", 1747);
        mapTypeAccount.put("Cuenta de crédito", 1748);
        mapTypeAccount.put("Cuenta de débito", 1749);
        mapTypeAccount.put("Cuenta de crédito", 1750);*/
        for (Map.Entry entry : mapTypeAccount.entrySet()) {
            Object TypeAccount = entry.getKey();
            jCmbBoxTypeAccount.addItem((String) TypeAccount);
        }

    }

    HashMap<String, Integer> map = new HashMap<>();

    public void Cities() {
        map.put("Cali", 1902);
        map.put("Barrancabermeja", 1903);
        map.put("Bogotá", 1904);
        map.put("Medellín", 1905);
        map.put("Barranquilla", 1906);
        map.put("Cartagena", 1907);
        map.put("Soacha", 1908);
        map.put("Cúcuta", 1909);
        map.put("Soledad", 1910);
        map.put("Bucaramanga", 1911);
        map.put("Bello", 1912);
        map.put("Valledupar", 1913);
        map.put("Villavicencio", 1914);
        map.put("Santa Marta", 1915);
        map.put("Ibagué", 1916);
        map.put("Montería", 1917);
        map.put("Pereira", 1918);
        map.put("Manizales", 1919);
        map.put("Pasto", 1920);
        map.put("Neiva", 1921);
        map.put("Palmira", 1922);
        map.put("Popayán", 1923);
        map.put("Buenaventura", 1924);
        map.put("Armenia", 1925);
        map.put("Floridablanca", 1926);
        map.put("Sincelejo", 1927);
        map.put("Itagüí", 1928);
        map.put("Tumaco", 1929);
        map.put("Envigado", 1930);
        map.put("Dosquebradas", 1931);
        map.put("Tuluá", 1932);
        map.put("Barrancabermeja", 1933);
        map.put("Riohcha", 1934);
        map.put("Uribia", 1935);
        map.put("Maicao", 1936);
        map.put("Piedecuesta", 1937);
        map.put("Tunja", 1938);
        map.put("Yopal", 1939);
        map.put("Florencia", 1940);
        map.put("Girón", 1941);
        map.put("Facatativa", 1942);
        map.put("Jamundí", 1943);
        map.put("Fusagasugá", 1944);
        map.put("Mosquera", 1945);
        map.put("Chía", 1946);
        map.put("Zipaquirá", 1947);
        map.put("Rionegro", 1948);
        map.put("Malambo", 1949);
        map.put("Magangué", 1950);
        map.put("Madrid", 1951);
        map.put("Cartago", 1952);
        map.put("Turbo", 1953);
        map.put("Quibdó", 1954);
        map.put("Apartadó", 1955);
        map.put("Sogamoso", 1956);
        map.put("Ocaña", 1957);
        map.put("Pitalito", 1958);
        map.put("Buga", 1959);
        map.put("Duitama", 1960);
        map.put("Ciénaga", 1961);
        map.put("Aguachica", 1962);
        map.put("Girardot", 1963);
        map.put("Lorica", 1964);
        map.put("Turbaco", 1965);
        map.put("Ipiales", 1966);
        map.put("Funza", 1967);
        map.put("Santander de Quilichao ", 1968);
        map.put("Villa del Rosario", 1969);
        map.put("Sahagún", 1970);
        map.put("Yumbo", 1971);
        map.put("Cereté", 1972);
        map.put("Sabanalarga", 1973);
        map.put("Cajicá", 1974);
        map.put("Arauca", 1975);
        map.put("Caucasia", 1976);
        map.put("Los Patios", 1977);
        map.put("Manaure", 1978);
        map.put("Tierralta", 1979);
        map.put("Candelaria", 1980);
        map.put("Acacías", 1981);
        map.put("Sabaneta", 1982);
        map.put("Montelíbano", 1983);
        map.put("Caldas", 1984);
        map.put("Copacabana", 1985);
        map.put("Cumaribo", 1986);
        map.put("Santa Rosa de Cabal", 1987);
        map.put("La Estrella", 1988);
        map.put("Calarcá", 1989);
        map.put("Zona Bananera", 1990);
        map.put("Arjona", 1991);
        map.put("La Dorada", 1992);
        map.put("Garzón", 1993);
        map.put("El Carmen de Bolivar", 1994);

        for (Map.Entry entry : map.entrySet()) {
            Object City = entry.getKey();
            jCmbBoxCities.addItem((String) City);
        }

    }

    public void updateProviders() throws UnsupportedEncodingException, IOException {
        String apiUrl = "https://black-diamond.com.co/API/public/api/providers/" + id + "?key=EXaR0JoKIirohPwbRPIHc3s73Oygi0XV";
        URL url = new URL(apiUrl);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("PUT");
        conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

        Map<String, Object> data = new LinkedHashMap<>();
        data.put("legal_name", jTxtLegalName.getText());
        data.put("commercial_name", jTxtCommercialName.getText());
        data.put("email", jTxtEmail.getText());
        data.put("phone", jTxtPhone.getText());
        data.put("address", jTxtAddrees.getText());
        data.put("param_city", jTxtCities.getText());
        data.put("name_contact", jTxtNameContact.getText());
        data.put("param_bank", jTxtBank.getText());
        data.put("param_account", jTxtTypeAccount.getText());
        data.put("account", jTxtAccount.getText());
        data.put("param_state", "1651");

        StringBuilder putData = new StringBuilder();
        for (Map.Entry<String, Object> param : data.entrySet()) {
            if (putData.length() != 0) {
                putData.append('&');
            }

            putData.append(URLEncoder.encode(param.getKey(), "UTF-8"));
            putData.append('=');
            putData.append(URLEncoder.encode(String.valueOf(param.getValue()), "UTF-8"));
        }

        byte[] putDataBytes = putData.toString().getBytes(StandardCharsets.UTF_8);
        conn.setRequestProperty("Content-Length", String.valueOf(putDataBytes.length));
        conn.setDoOutput(true);
        conn.getOutputStream().write(putDataBytes);

        try (Reader in = new BufferedReader(new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
            int c;
            while ((c = in.read()) != -1) {
                System.out.print((char) c);
            }
        }
    }
}
