/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class EditUser extends javax.swing.JDialog {

    private static userBean uB = new userBean("", "", "", "", "", "", "", "", "");
    public int id;

    public int cities;

    public EditUser(java.awt.Frame parent, boolean modal, userBean temp) {
        super(parent, modal);
        initComponents();
        Cities();
        Rol();
        Gender();
        TypeUser();
        jTxtCities.setVisible(false);
        jTxtRol.setVisible(false);
        jTxtGender.setVisible(false);
        jTxtTypeUser.setVisible(false);
        jCmbBoxCities.setSelectedItem(null);
        jCmbBoxRol.setSelectedItem(null);
        jCmbBoxTypeUser.setSelectedItem(null);
        jCmbBoxGender.setSelectedItem(null);
        id = Integer.parseInt(temp.getId());
        this.jTxtName.setText(temp.getFirstName());
        this.jTxtLastName.setText(temp.getLastName());
        this.jTxtBirthday.setText(temp.getBirthday());
        this.jTxtAddress.setText(temp.getAddress());
        this.jTxtEmail.setText(temp.getEmail());

        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/IMG/Logo.jpeg");
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jCmbBoxTypeUser = new javax.swing.JComboBox<>();
        jTxtBirthday = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCmbBoxRol = new javax.swing.JComboBox<>();
        jBtnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jBtnCancel = new javax.swing.JButton();
        jCmbBoxGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCmbBoxState = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTxtCities = new javax.swing.JTextField();
        jCmbBoxCities = new javax.swing.JComboBox<>();
        jTxtRol = new javax.swing.JTextField();
        jTxtTypeUser = new javax.swing.JTextField();
        jTxtGender = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLog_out1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(236, 233, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel4.setText("Nombre");

        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setText("Ciudad / Municipio");

        jTxtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel9.setText("Apellido");

        jLabel10.setText("Direccion");

        jLabel11.setText("Rol");

        jTxtLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jTxtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jCmbBoxTypeUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxTypeUserActionPerformed(evt);
            }
        });

        jTxtBirthday.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel2.setText("Tipo de Usuario");

        jCmbBoxRol.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxRolActionPerformed(evt);
            }
        });

        jBtnSave.setBackground(new java.awt.Color(204, 102, 0));
        jBtnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnSave.setText("Guardar");
        jBtnSave.setBorderPainted(false);
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo electronico");

        jTxtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jBtnCancel.setBackground(new java.awt.Color(204, 102, 0));
        jBtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnCancel.setText("Cancelar");
        jBtnCancel.setBorderPainted(false);
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jCmbBoxGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxGenderActionPerformed(evt);
            }
        });

        jLabel14.setText("Genero");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("EDITAR USUARIO");

        jCmbBoxState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo" }));
        jCmbBoxState.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel7.setText("Estado");

        jTxtCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCitiesActionPerformed(evt);
            }
        });

        jCmbBoxCities.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxCitiesActionPerformed(evt);
            }
        });

        jTxtRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRolActionPerformed(evt);
            }
        });

        jTxtTypeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTypeUserActionPerformed(evt);
            }
        });

        jTxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(286, 286, 286))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jTxtBirthday)
                                .addGap(147, 147, 147))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addGap(338, 338, 338))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jCmbBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtName, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(jTxtEmail))
                                    .addComponent(jCmbBoxCities, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCmbBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(168, 168, 168))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCmbBoxTypeUser, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCmbBoxRol, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTxtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCmbBoxTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jCmbBoxCities, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbBoxState, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSave)
                    .addComponent(jBtnCancel)
                    .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButtonLog_out1.setBackground(new java.awt.Color(204, 102, 0));
        jButtonLog_out1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLog_out1.setText("Cerrar Sesión");
        jButtonLog_out1.setBorderPainted(false);
        jButtonLog_out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLog_out1ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ayuda33.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLog_out1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButtonLog_out1))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLog_out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLog_out1ActionPerformed

        Login newframe = new Login();
        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonLog_out1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Users newframe = new Users();
        newframe.setVisible(true);

        this.dispose();    }//GEN-LAST:event_jButton8ActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        /*clear();*/
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        try {
            UpdateUser();
            JOptionPane.showMessageDialog(null, "Usuario actualizado");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jCmbBoxTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxTypeUserActionPerformed
        String TypeUser = (String) jCmbBoxTypeUser.getSelectedItem();
        jTxtTypeUser.setText(String.valueOf(mapUser.get(TypeUser)));
    }//GEN-LAST:event_jCmbBoxTypeUserActionPerformed

    private void jCmbBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxRolActionPerformed
        String Rol = (String) jCmbBoxRol.getSelectedItem();
        jTxtRol.setText(String.valueOf(mapAdmin.get(Rol)));
    }//GEN-LAST:event_jCmbBoxRolActionPerformed

    private void jTxtCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCitiesActionPerformed

    private void jCmbBoxCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxCitiesActionPerformed
        String City = (String) jCmbBoxCities.getSelectedItem();
        jTxtCities.setText(String.valueOf(map.get(City)));
    }//GEN-LAST:event_jCmbBoxCitiesActionPerformed

    private void jTxtRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRolActionPerformed

    private void jTxtTypeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTypeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTypeUserActionPerformed

    private void jTxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGenderActionPerformed

    private void jCmbBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxGenderActionPerformed
        String Gender = (String) jCmbBoxGender.getSelectedItem();
        jTxtGender.setText(String.valueOf(mapGender.get(Gender)));
    }//GEN-LAST:event_jCmbBoxGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditUser dialog = new EditUser(new javax.swing.JFrame(), true, uB);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonLog_out1;
    public static javax.swing.JComboBox<String> jCmbBoxCities;
    public static javax.swing.JComboBox<String> jCmbBoxGender;
    public static javax.swing.JComboBox<String> jCmbBoxRol;
    private javax.swing.JComboBox<String> jCmbBoxState;
    public static javax.swing.JComboBox<String> jCmbBoxTypeUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField jTxtAddress;
    public static javax.swing.JTextField jTxtBirthday;
    public static javax.swing.JTextField jTxtCities;
    public static javax.swing.JTextField jTxtEmail;
    public static javax.swing.JTextField jTxtGender;
    public static javax.swing.JTextField jTxtLastName;
    public static javax.swing.JTextField jTxtName;
    public static javax.swing.JTextField jTxtRol;
    public static javax.swing.JTextField jTxtTypeUser;
    // End of variables declaration//GEN-END:variables
    HashMap<String, Integer> map = new HashMap<>();
    HashMap<String, Integer> mapUser = new HashMap<>();
    HashMap<String, Integer> mapGender = new HashMap<>();

    HashMap<String, Integer> mapAdmin = new HashMap<>();

    public void Rol() {
        mapAdmin.put("Administrador Master", 3403);
        mapAdmin.put("Administrador de Productos", 3404);
        mapAdmin.put("Administrador de Ventas", 3405);

        for (Map.Entry entry : mapAdmin.entrySet()) {
            Object Rol = entry.getKey();
            jCmbBoxRol.addItem((String) Rol);
        }
    }

    public void TypeUser() {
        mapUser.put("Usuario", 235);
        mapUser.put("Cliente", 236);

        for (Map.Entry entry : mapUser.entrySet()) {
            Object TypeUser = entry.getKey();
            jCmbBoxTypeUser.addItem((String) TypeUser);
        }
    }

    public void Gender() {
        mapGender.put("Masculino", 1601);
        mapGender.put("Femenino", 1602);

        for (Map.Entry entry : mapGender.entrySet()) {
            Object Gender = entry.getKey();
            jCmbBoxGender.addItem((String) Gender);
        }
    }

    public void Cities() {
        map.put("Cali", 1902);
        map.put("Barrancabermeja", 1903);
        map.put("Bogotá", 1904);
        map.put("Medellín", 1905);
        map.put("Barranquilla", 1906);
        map.put("Cartagena", 1907);
        map.put("Soacha", 1908);
        map.put("Cúcuta", 1909);
        map.put("Soledad", 1910);
        map.put("Bucaramanga", 1911);
        map.put("Bello", 1912);
        map.put("Valledupar", 1913);
        map.put("Villavicencio", 1914);
        map.put("Santa Marta", 1915);
        map.put("Ibagué", 1916);
        map.put("Montería", 1917);
        map.put("Pereira", 1918);
        map.put("Manizales", 1919);
        map.put("Pasto", 1920);
        map.put("Neiva", 1921);
        map.put("Palmira", 1922);
        map.put("Popayán", 1923);
        map.put("Buenaventura", 1924);
        map.put("Armenia", 1925);
        map.put("Floridablanca", 1926);
        map.put("Sincelejo", 1927);
        map.put("Itagüí", 1928);
        map.put("Tumaco", 1929);
        map.put("Envigado", 1930);
        map.put("Dosquebradas", 1931);
        map.put("Tuluá", 1932);
        map.put("Barrancabermeja", 1933);
        map.put("Riohcha", 1934);
        map.put("Uribia", 1935);
        map.put("Maicao", 1936);
        map.put("Piedecuesta", 1937);
        map.put("Tunja", 1938);
        map.put("Yopal", 1939);
        map.put("Florencia", 1940);
        map.put("Girón", 1941);
        map.put("Facatativa", 1942);
        map.put("Jamundí", 1943);
        map.put("Fusagasugá", 1944);
        map.put("Mosquera", 1945);
        map.put("Chía", 1946);
        map.put("Zipaquirá", 1947);
        map.put("Rionegro", 1948);
        map.put("Malambo", 1949);
        map.put("Magangué", 1950);
        map.put("Madrid", 1951);
        map.put("Cartago", 1952);
        map.put("Turbo", 1953);
        map.put("Quibdó", 1954);
        map.put("Apartadó", 1955);
        map.put("Sogamoso", 1956);
        map.put("Ocaña", 1957);
        map.put("Pitalito", 1958);
        map.put("Buga", 1959);
        map.put("Duitama", 1960);
        map.put("Ciénaga", 1961);
        map.put("Aguachica", 1962);
        map.put("Girardot", 1963);
        map.put("Lorica", 1964);
        map.put("Turbaco", 1965);
        map.put("Ipiales", 1966);
        map.put("Funza", 1967);
        map.put("Santander de Quilichao ", 1968);
        map.put("Villa del Rosario", 1969);
        map.put("Sahagún", 1970);
        map.put("Yumbo", 1971);
        map.put("Cereté", 1972);
        map.put("Sabanalarga", 1973);
        map.put("Cajicá", 1974);
        map.put("Arauca", 1975);
        map.put("Caucasia", 1976);
        map.put("Los Patios", 1977);
        map.put("Manaure", 1978);
        map.put("Tierralta", 1979);
        map.put("Candelaria", 1980);
        map.put("Acacías", 1981);
        map.put("Sabaneta", 1982);
        map.put("Montelíbano", 1983);
        map.put("Caldas", 1984);
        map.put("Copacabana", 1985);
        map.put("Cumaribo", 1986);
        map.put("Santa Rosa de Cabal", 1987);
        map.put("La Estrella", 1988);
        map.put("Calarcá", 1989);
        map.put("Zona Bananera", 1990);
        map.put("Arjona", 1991);
        map.put("La Dorada", 1992);
        map.put("Garzón", 1993);
        map.put("El Carmen de Bolivar", 1994);

        for (Map.Entry entry : map.entrySet()) {
            Object City = entry.getKey();
            jCmbBoxCities.addItem((String) City);
        }

    }

    public void UpdateUser() throws MalformedURLException, UnsupportedEncodingException, IOException {

        String apiUrl = "https://black-diamond.com.co/API/public/api/users/" + id + "?key=EXaR0JoKIirohPwbRPIHc3s73Oygi0XV";
        URL url = new URL(apiUrl);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        //Method put
        conn.setRequestMethod("PUT");
        conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");

        Map<String, Object> data = new LinkedHashMap<>();
        // Agrega los campos y valores que deseas actualizar
        data.put("first_name", jTxtName.getText());
        data.put("last_name", jTxtLastName.getText());
        data.put("birthday", jTxtBirthday.getText());
        data.put("address", jTxtAddress.getText());
        data.put("email", jTxtEmail.getText());
        data.put("param_city", jTxtCities.getText());
        data.put("type_user", jTxtTypeUser.getText());
        data.put("param_gender", jTxtGender.getText());
        data.put("image", "default.jpg");
        data.put("param_rol", jTxtRol.getText());
        data.put("param_state", "1651");

        StringBuilder putData = new StringBuilder();
        for (Map.Entry<String, Object> param : data.entrySet()) {
            if (putData.length() != 0) {
                putData.append('&');
            }

            putData.append(URLEncoder.encode(param.getKey(), "UTF-8"));
            putData.append('=');
            putData.append(URLEncoder.encode(String.valueOf(param.getValue()), "UTF-8"));
        }

        byte[] putDataBytes = putData.toString().getBytes("UTF-8");
        conn.setRequestProperty("Content-Length", String.valueOf(putDataBytes.length));
        conn.setDoOutput(true);
        conn.getOutputStream().write(putDataBytes);

        Reader in = new BufferedReader(new InputStreamReader(conn.getInputStream(), "UTF-8"));
        for (int c = in.read(); c != -1; c = in.read()) {
            System.out.print((char) c);
        }
    }
}
