/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public RegisterUser() throws IOException {
        initComponents();
        createUser();
        Cities();
        Rol();
        Gender();
        jTxtCities.setVisible(false);
        jTxtRol.setVisible(false);
        jTxtGender.setVisible(false);
        jCmbBoxCities.setSelectedItem(null);
        jCmbBoxRol.setSelectedItem(null);
        jCmbBoxGender.setSelectedItem(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/IMG/Logo.jpeg");
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jCmbBoxCities = new javax.swing.JComboBox<>();
        jTxtBirthday = new javax.swing.JTextField();
        jBtnUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jBtnShow = new javax.swing.JButton();
        jBtnShow2 = new javax.swing.JButton();
        jFieldPassword = new javax.swing.JPasswordField();
        jFieldPassword2 = new javax.swing.JPasswordField();
        jCmbBoxGender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jCmbBoxRol = new javax.swing.JComboBox<>();
        jTxtCities = new javax.swing.JTextField();
        jTxtRol = new javax.swing.JTextField();
        jTxtGender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ayuda33.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("REGISTRO USUARIO");

        jPanel4.setBackground(new java.awt.Color(236, 233, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel4.setText("Nombre");

        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setText("Ciudad / Municipio");

        jTxtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel9.setText("Apellido");

        jLabel10.setText("Direccion");

        jLabel11.setText("Rol");

        jTxtLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jTxtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jCmbBoxCities.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxCitiesActionPerformed(evt);
            }
        });

        jTxtBirthday.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jBtnUser.setBackground(new java.awt.Color(204, 102, 0));
        jBtnUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnUser.setText("Crear Usuario");
        jBtnUser.setBorderPainted(false);
        jBtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo electronico");

        jTxtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel12.setText("Contraseña");

        jBtnCancel.setBackground(new java.awt.Color(204, 102, 0));
        jBtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnCancel.setText("Cancelar");
        jBtnCancel.setBorderPainted(false);
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jLabel13.setText("Verificar Contraseña");

        jBtnShow.setText("Mostrar");
        jBtnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowActionPerformed(evt);
            }
        });

        jBtnShow2.setText("Mostrar");
        jBtnShow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShow2ActionPerformed(evt);
            }
        });

        jFieldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldPasswordActionPerformed(evt);
            }
        });

        jFieldPassword2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jFieldPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldPassword2ActionPerformed(evt);
            }
        });

        jCmbBoxGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));

        jLabel14.setText("Genero");

        jCmbBoxRol.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        jCmbBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbBoxRolActionPerformed(evt);
            }
        });

        jTxtCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCitiesActionPerformed(evt);
            }
        });

        jTxtRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRolActionPerformed(evt);
            }
        });

        jTxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTxtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jBtnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(286, 286, 286))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addGap(295, 295, 295))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtBirthday)
                                        .addComponent(jCmbBoxCities, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)
                                        .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jCmbBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addGap(168, 168, 168))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jFieldPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(jFieldPassword2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(jCmbBoxRol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnShow)
                                            .addComponent(jBtnShow2))))
                                .addContainerGap(145, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbBoxCities, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnShow)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCmbBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jTxtCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnShow2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnUser)
                        .addComponent(jBtnCancel))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Login newframe = new Login();
        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCmbBoxCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxCitiesActionPerformed
        String City = (String) jCmbBoxCities.getSelectedItem();
        jTxtCities.setText(String.valueOf(map.get(City)));
    }//GEN-LAST:event_jCmbBoxCitiesActionPerformed

    private void jBtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserActionPerformed
        try {
            createUser();
            JOptionPane.showMessageDialog(null, "Usuario creado");
            Users x = new Users();
            x.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnUserActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        clear();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowActionPerformed
        showPass();

    }//GEN-LAST:event_jBtnShowActionPerformed

    private void jFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldPasswordActionPerformed

    }//GEN-LAST:event_jFieldPasswordActionPerformed

    private void jFieldPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldPassword2ActionPerformed

    private void jBtnShow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShow2ActionPerformed
        showPass2();
    }//GEN-LAST:event_jBtnShow2ActionPerformed

    private void jTxtCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCitiesActionPerformed

    private void jTxtRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRolActionPerformed

    private void jTxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGenderActionPerformed

    private void jCmbBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbBoxRolActionPerformed
        String Rol = (String) jCmbBoxRol.getSelectedItem();
        jTxtRol.setText(String.valueOf(mapAdmin.get(Rol)));
    }//GEN-LAST:event_jCmbBoxRolActionPerformed
//Logic of register 

    //Show password
    private boolean pass = false;

    public void showPass() {

        if (pass) {
            jFieldPassword.setEchoChar('*');
        } else {
            jFieldPassword.setEchoChar('\u0000');
        }

        pass = !pass;
    }

    private boolean pass2 = false;

    public void showPass2() {
        if (pass2) {
            jFieldPassword2.setEchoChar('*');
        } else {
            jFieldPassword2.setEchoChar('\u0000');
        }

        pass2 = !pass2;
    }
//Connetion a la API 
/*Crea un mapa de datos que almacena los valores de los campos 
    de texto, las contraseñas y los combobox del formulario.
     */
    public void createUser() throws UnsupportedEncodingException, IOException {
        String password = new String(jFieldPassword.getPassword());
        String password2 = new String(jFieldPassword2.getPassword());
        //validar que las contraseñas coincidan
        if (!password.equals(password2)) {
            //mostrar un mensaje de error y salir del método
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
        URL url = new URL("https://black-diamond.com.co/API/public/api/register");
        Map<String, Object> data = new LinkedHashMap<>();

        //obtener los valores de los campos de texto y las contraseñas
        String firstName = jTxtName.getText();
        String lastName = jTxtLastName.getText();
        String birthday = jTxtBirthday.getText();
        String address = jTxtAddress.getText();
        String email = jTxtEmail.getText();
        String city = (String) jCmbBoxCities.getSelectedItem();
        String rol = (String) jCmbBoxRol.getSelectedItem();
        String gender = (String) jCmbBoxGender.getSelectedItem();

//Agrega los datos al mapa con las claves correspondientes a la API.
        data.put("first_name", firstName);
        data.put("last_name", lastName);
        data.put("birthday", birthday);
        data.put("address", address);
        data.put("param_city", "1902");
        data.put("type_user", "235");
        data.put("param_gender", "1602");
        data.put("image", "default.jpg");
        data.put("email", email);
        data.put("param_rol", "3403");
        data.put("param_state", "1651");
        data.put("password", password);
        //Creación un cadena de texto que contiene los datos codificados en formato URL, separados por el símbolo &.
        StringBuilder postData = new StringBuilder();
        for (Map.Entry<String, Object> param : data.entrySet()) {
            if (postData.length() != 0) {
                postData.append('&');
                //La cadena de texto con los datos codificados en un arreglo de bytes, usando la codificación UTF-8.    
            }
            postData.append(URLEncoder.encode(param.getKey(), "UTF-8"));
            postData.append('=');
            postData.append(URLEncoder.encode(String.valueOf(param.getValue()),
                    "UTF-8"));
        }
        byte[] postDataBytes = postData.toString().getBytes("UTF-8");
        /* conexión HTTP con la URL del servicio web, y configura el método de solicitud como POST, 
        el tipo de contenido como application/x-www-form-urlencoded 
        y la longitud del contenido como el número de bytes de los datos.*/
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type",
                "application/x-www-form-urlencoded");
        conn.setRequestProperty("Content-Length",
                String.valueOf(postDataBytes.length));
        //Se habilita la salida de datos y escribe los bytes de los datos en el flujo de salida de la conexión.

        conn.setDoOutput(true);
        conn.getOutputStream().write(postDataBytes);

        /*Creación de un lector que lee la entrada de datos desde el flujo de entrada de la conexión, 
        usando la codificación UTF-8.*/
 /*Ciclo for para recorre los caracteres que lee desde el lector y los imprime en la consola. 
        Estos caracteres corresponden a la respuesta de la API*/
        Reader in = new BufferedReader(new InputStreamReader(
                conn.getInputStream(), "UTF-8"));
        for (int c = in.read(); c != -1; c = in.read()) {
            System.out.print((char) c);
        }
    }

    public void clear() {
        jFieldPassword.setText("");
        jFieldPassword2.setText("");
        jTxtAddress.setText("");
        jTxtBirthday.setText("");
        jTxtEmail.setText("");
        jTxtLastName.setText("");
        jTxtName.setText("");
        jCmbBoxGender.setSelectedItem(null);
        jCmbBoxRol.setSelectedItem(null);
        //jCmbBoxState.setSelectedItem(null);
        //jCmbBoxTypeUser.setSelectedItem(null);
        jCmbBoxCities.setSelectedItem(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterUser().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnShow;
    private javax.swing.JButton jBtnShow2;
    private javax.swing.JButton jBtnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    public static javax.swing.JComboBox<String> jCmbBoxCities;
    public static javax.swing.JComboBox<String> jCmbBoxGender;
    public static javax.swing.JComboBox<String> jCmbBoxRol;
    private javax.swing.JPasswordField jFieldPassword;
    private javax.swing.JPasswordField jFieldPassword2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtBirthday;
    public static javax.swing.JTextField jTxtCities;
    private javax.swing.JTextField jTxtEmail;
    public static javax.swing.JTextField jTxtGender;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtName;
    public static javax.swing.JTextField jTxtRol;
    // End of variables declaration//GEN-END:variables
    HashMap<String, Integer> mapAdmin = new HashMap<>();
    HashMap<String, Integer> map = new HashMap<>();
    HashMap<String, Integer> mapGender = new HashMap<>();

    public void Rol() {
        mapAdmin.put("Administrador Master", 3403);
        mapAdmin.put("Administrador de Productos", 3404);
        mapAdmin.put("Administrador de Ventas", 3405);

        for (Map.Entry entry : mapAdmin.entrySet()) {
            Object Rol = entry.getKey();
            jCmbBoxRol.addItem((String) Rol);
        }
    }

    public void Gender() {
        mapGender.put("Masculino", 1601);
        mapGender.put("Femenino", 1602);

        for (Map.Entry entry : mapGender.entrySet()) {
            Object Gender = entry.getKey();
            jCmbBoxGender.addItem((String) Gender);
        }
    }

    public void Cities() {
        map.put("Cali", 1902);
        map.put("Barrancabermeja", 1903);
        map.put("Bogotá", 1904);
        map.put("Medellín", 1905);
        map.put("Barranquilla", 1906);
        map.put("Cartagena", 1907);
        map.put("Soacha", 1908);
        map.put("Cúcuta", 1909);
        map.put("Soledad", 1910);
        map.put("Bucaramanga", 1911);
        map.put("Bello", 1912);
        map.put("Valledupar", 1913);
        map.put("Villavicencio", 1914);
        map.put("Santa Marta", 1915);
        map.put("Ibagué", 1916);
        map.put("Montería", 1917);
        map.put("Pereira", 1918);
        map.put("Manizales", 1919);
        map.put("Pasto", 1920);
        map.put("Neiva", 1921);
        map.put("Palmira", 1922);
        map.put("Popayán", 1923);
        map.put("Buenaventura", 1924);
        map.put("Armenia", 1925);
        map.put("Floridablanca", 1926);
        map.put("Sincelejo", 1927);
        map.put("Itagüí", 1928);
        map.put("Tumaco", 1929);
        map.put("Envigado", 1930);
        map.put("Dosquebradas", 1931);
        map.put("Tuluá", 1932);
        map.put("Barrancabermeja", 1933);
        map.put("Riohcha", 1934);
        map.put("Uribia", 1935);
        map.put("Maicao", 1936);
        map.put("Piedecuesta", 1937);
        map.put("Tunja", 1938);
        map.put("Yopal", 1939);
        map.put("Florencia", 1940);
        map.put("Girón", 1941);
        map.put("Facatativa", 1942);
        map.put("Jamundí", 1943);
        map.put("Fusagasugá", 1944);
        map.put("Mosquera", 1945);
        map.put("Chía", 1946);
        map.put("Zipaquirá", 1947);
        map.put("Rionegro", 1948);
        map.put("Malambo", 1949);
        map.put("Magangué", 1950);
        map.put("Madrid", 1951);
        map.put("Cartago", 1952);
        map.put("Turbo", 1953);
        map.put("Quibdó", 1954);
        map.put("Apartadó", 1955);
        map.put("Sogamoso", 1956);
        map.put("Ocaña", 1957);
        map.put("Pitalito", 1958);
        map.put("Buga", 1959);
        map.put("Duitama", 1960);
        map.put("Ciénaga", 1961);
        map.put("Aguachica", 1962);
        map.put("Girardot", 1963);
        map.put("Lorica", 1964);
        map.put("Turbaco", 1965);
        map.put("Ipiales", 1966);
        map.put("Funza", 1967);
        map.put("Santander de Quilichao ", 1968);
        map.put("Villa del Rosario", 1969);
        map.put("Sahagún", 1970);
        map.put("Yumbo", 1971);
        map.put("Cereté", 1972);
        map.put("Sabanalarga", 1973);
        map.put("Cajicá", 1974);
        map.put("Arauca", 1975);
        map.put("Caucasia", 1976);
        map.put("Los Patios", 1977);
        map.put("Manaure", 1978);
        map.put("Tierralta", 1979);
        map.put("Candelaria", 1980);
        map.put("Acacías", 1981);
        map.put("Sabaneta", 1982);
        map.put("Montelíbano", 1983);
        map.put("Caldas", 1984);
        map.put("Copacabana", 1985);
        map.put("Cumaribo", 1986);
        map.put("Santa Rosa de Cabal", 1987);
        map.put("La Estrella", 1988);
        map.put("Calarcá", 1989);
        map.put("Zona Bananera", 1990);
        map.put("Arjona", 1991);
        map.put("La Dorada", 1992);
        map.put("Garzón", 1993);
        map.put("El Carmen de Bolivar", 1994);

        for (Map.Entry entry : map.entrySet()) {
            Object City = entry.getKey();
            jCmbBoxCities.addItem((String) City);
        }

    }
}
