/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 *
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Users() {

        initComponents();
        getUsers();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/IMG/Logo.jpeg");
    }

    public void getUsers() {
        try {
            URL uri = new URL("https://black-diamond.com.co/API/public/api/users?key=EXaR0JoKIirohPwbRPIHc3s73Oygi0XV");
            HttpURLConnection connection = (HttpURLConnection) uri.openConnection();
            connection.setRequestMethod("GET");
            connection.connect();

            //get code http of request
            int responseCode = connection.getResponseCode();

            //validation code http
            if (responseCode != 200) {
                throw new RuntimeException("Error" + responseCode);
            } else {
                StringBuilder data = new StringBuilder();
                Scanner scanner = new Scanner(uri.openStream());
                while (scanner.hasNext()) {
                    data.append(scanner.nextLine());
                }

                scanner.close();
                System.out.println(data.toString());

                JSONObject jsonData = new JSONObject(data.toString());
                JSONArray array = jsonData.getJSONArray("data");

                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Id");
                model.addColumn("Nombre");
                model.addColumn("Apellidos");
                model.addColumn("Fecha de nacimiento");
                model.addColumn("Dirección");
                model.addColumn("Ciudad");
                model.addColumn("Tipo de usuario");
                model.addColumn("Genero");
                model.addColumn("Foto de perfil");
                model.addColumn("Correo");
                model.addColumn("Rol");
                model.addColumn("Estado");

                for (int i = 0; i < array.length(); i++) {
                    JSONObject dataArray = array.getJSONObject(i);

                    Object[] obj = new Object[12];
                    obj[0] = dataArray.getInt("id");
                    obj[1] = dataArray.getString("first_name");
                    obj[2] = dataArray.getString("last_name");
                    obj[3] = dataArray.getString("birthday");
                    obj[4] = dataArray.getString("address");
                    obj[5] = dataArray.getString("param_city");
                    obj[6] = dataArray.getString("type_user");
                    obj[7] = dataArray.getString("param_gender");
                    obj[8] = dataArray.getString("image");
                    obj[9] = dataArray.getString("email");
                    obj[10] = dataArray.getString("param_rol");
                    obj[11] = dataArray.getString("param_state");
                    model.addRow(obj);

                }
                jTableUsers.setModel(model);

            }
        } catch (Exception e) {
            System.err.println("404:" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonNew_User = new javax.swing.JButton();
        jButtonEdit_User = new javax.swing.JButton();
        jButtonDelete_User = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonUsers = new javax.swing.JButton();
        jButtonProveedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ayuda33.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton1))
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("USUARIOS");

        jButtonNew_User.setBackground(new java.awt.Color(204, 102, 0));
        jButtonNew_User.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonNew_User.setText("Nuevo");
        jButtonNew_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNew_UserActionPerformed(evt);
            }
        });

        jButtonEdit_User.setBackground(new java.awt.Color(204, 102, 0));
        jButtonEdit_User.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonEdit_User.setText("Editar");
        jButtonEdit_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdit_UserActionPerformed(evt);
            }
        });

        jButtonDelete_User.setBackground(new java.awt.Color(204, 102, 0));
        jButtonDelete_User.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonDelete_User.setText("Eliminar");
        jButtonDelete_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete_UserActionPerformed(evt);
            }
        });

        jTableUsers.setAutoCreateRowSorter(true);
        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", "", "", "", "", "", "", ""},
                {null, "", null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Fecha nacimiento", "direccion", "Ciudad / Municipio", "Tipo de usuario", "Correo ", "Contraseña", "Rol", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsers.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableUsersComponentAdded(evt);
            }
        });
        jTableUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsersMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableUsersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsers);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButtonUsers.setBackground(new java.awt.Color(204, 102, 0));
        jButtonUsers.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonUsers.setText("Usuarios");
        jButtonUsers.setBorderPainted(false);
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jButtonProveedores.setBackground(new java.awt.Color(204, 204, 204));
        jButtonProveedores.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setBorderPainted(false);
        jButtonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonUsers)
                .addGap(94, 94, 94)
                .addComponent(jButtonProveedores)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonNew_User)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEdit_User)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelete_User))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew_User)
                    .addComponent(jButtonEdit_User)
                    .addComponent(jButtonDelete_User))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(142, 142, 142))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login newframe = new Login();
        newframe.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        Users newframe = new Users();
        newframe.setVisible(true);

        this.dispose();    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonNew_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNew_UserActionPerformed
        // TODO add your handling code here:
        RegisterUser newframe = null;
        try {
            newframe = new RegisterUser();
        } catch (IOException ex) {
            Logger.getLogger(Users.class.getName()).log(Level.SEVERE, null, ex);
        }
        newframe.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButtonNew_UserActionPerformed

    private void jButtonEdit_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdit_UserActionPerformed
        if (jTableUsers.getSelectedRow() == -1) {
            return;
        }
        userBean u = new userBean("", "", "", "", "","", "", "","");
        int i = jTableUsers.getSelectedRow();
        String id = jTableUsers.getValueAt(i, 0).toString();
        String firstName = jTableUsers.getValueAt(i, 1).toString();
        String lastName = jTableUsers.getValueAt(i, 2).toString();
        String birthday = jTableUsers.getValueAt(i, 3).toString();
        String address = jTableUsers.getValueAt(i, 4).toString();
        String image = jTableUsers.getValueAt(i, 8).toString();
        String email = jTableUsers.getValueAt(i, 9).toString();
        String password = jTableUsers.getValueAt(i, 10).toString();

        u.setId(id);
        u.setFirstName(firstName);
        u.setLastName(lastName);
        u.setBirthday(birthday);
        u.setAddres(address);
        u.setImage(image);
        u.setEmail(email);
        u.setPassword(password);

        EditUser x = new EditUser(this, true, u);
        x.setVisible(true);

    }//GEN-LAST:event_jButtonEdit_UserActionPerformed

    private void jTableUsersComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableUsersComponentAdded

    }//GEN-LAST:event_jTableUsersComponentAdded

    private void jTableUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsersMouseClicked
        /*int row = jTableUsers.getSelectedRow();
        DefaultTableModel model = new DefaultTableModel();
        jTableUsers.getModel();
        String[] data = new String[model.getColumnCount()];
        for (int i = 0; i < model.getColumnCount(); i++) {
            data[i] = model.getValueAt(row, i).toString();
            jTxtName.setText(data[i]);
        }
        int select = jTableUsers.rowAtPoint(evt.getPoint());
        jTxtName.setText(String.valueOf(jTableUsers.getValueAt(select, 1)));

         */

    }//GEN-LAST:event_jTableUsersMouseClicked

    private void jTableUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsersMousePressed
        int select = jTableUsers.rowAtPoint(evt.getPoint());
        String name = String.valueOf(jTableUsers.getValueAt(select, 1));

    }//GEN-LAST:event_jTableUsersMousePressed

    private void jButtonDelete_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete_UserActionPerformed

        if (jTableUsers.getSelectedRow() == -1) {
            return;
        }
        userBean u = new userBean("", "", "", "", "", "", "", "","");
        int i = jTableUsers.getSelectedRow();
        String id = jTableUsers.getValueAt(i, 0).toString();
        u.setId(id);
        DeleUser x = new DeleUser(this, true, u);
        x.setVisible(true);

    }//GEN-LAST:event_jButtonDelete_UserActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed
        // TODO add your handling code here:
        Providers newframe = new Providers();
        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonDelete_User;
    private javax.swing.JButton jButtonEdit_User;
    private javax.swing.JButton jButtonNew_User;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableUsers;
    // End of variables declaration//GEN-END:variables

}
